{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "source": [
    "from SagasuSubs import utils,models,patch\n",
    "from pathlib import Path\n",
    "\n",
    "patch.patch()"
   ],
   "outputs": [],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "source": [
    "workdir = Path('.') / 'subtitles' / 'subs_list'\n",
    "\n",
    "files = [*utils.iterate_files(workdir,'.ass')]\n",
    "\n",
    "files[:5]"
   ],
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "[PosixPath('subtitles/subs_list/animation/1970/(1970.4.1)明日之丈 第1季/BD/冷番补完字幕组/[冷番补完][明日之丈][あしたのジョー][01][480P][简体外挂].ass'),\n",
       " PosixPath('subtitles/subs_list/animation/1970/(1970.4.1)明日之丈 第1季/BD/冷番补完字幕组/[冷番补完][明日之丈][あしたのジョー][02][480P][简体外挂].ass'),\n",
       " PosixPath('subtitles/subs_list/animation/1970/(1970.4.1)明日之丈 第1季/BD/冷番补完字幕组/[冷番补完][明日之丈][あしたのジョー][03][480P][简体外挂].ass'),\n",
       " PosixPath('subtitles/subs_list/animation/1970/(1970.4.1)明日之丈 第1季/BD/冷番补完字幕组/[冷番补完][明日之丈][あしたのジョー][04][480P][简体外挂].ass'),\n",
       " PosixPath('subtitles/subs_list/animation/1970/(1970.4.1)明日之丈 第1季/BD/冷番补完字幕组/[冷番补完][明日之丈][あしたのジョー][05][480P][简体外挂].ass')]"
      ]
     },
     "metadata": {},
     "execution_count": 2
    }
   ],
   "metadata": {}
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "source": [
    "from tqdm.notebook import tqdm\n",
    "from traceback import format_exc\n",
    "\n",
    "for file in tqdm(files):\n",
    "    try:\n",
    "        models.SubtitlePersist.from_file(file,format='ass')\n",
    "    except Exception:\n",
    "        print(\n",
    "            '\\n-->\\t'.join(\n",
    "                [f'Error occurred during processing file {file}:'] +\n",
    "                format_exc(-3).splitlines()\n",
    "            )\n",
    "        )\n",
    "        \n",
    "    "
   ],
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "text/plain": [
       "  0%|          | 0/50231 [00:00<?, ?it/s]"
      ],
      "application/vnd.jupyter.widget-view+json": {
       "version_major": 2,
       "version_minor": 0,
       "model_id": "4c7b395cf12b45c0a672cdff2b585d76"
      }
     },
     "metadata": {}
    },
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "/home/mix/Documents/SagasuSubs/SagasuSubs/patch.py:59: UserWarning: Failed to parse field f='encoding',v='1Style: Karaoke0' due to ValueError(\"invalid literal for int() with base 10: '1Style: Karaoke0'\"), fallback to None\n",
      "  warn(f\"Failed to parse field {f=!r},{v=!r} due to {e!r}, fallback to None\")\n"
     ]
    },
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][11][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][01][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][02][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][03][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][04][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][05][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][06][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][07][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][08][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][09][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][12][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][13][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][14][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][15][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][16][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][17][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][18][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][19][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][20][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][21][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][22][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][23][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][24][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][25][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n",
      "Error occurred during processing file subtitles/subs_list/animation/2007/(2007.4.1)濑户之花嫁/BD/濑户之花嫁/[Seto_no_Hanayome][26][BDRIP][1920x1080][x264_FLAC].ass:\n",
      "-->\tTraceback (most recent call last):\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 129, in from_string\n",
      "-->\t    return cls.from_file(fp, format_, fps=fps, **kwargs)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/ssafile.py\", line 156, in from_file\n",
      "-->\t    format_ = autodetect_format(fragment)\n",
      "-->\t  File \"/home/mix/Documents/SagasuSubs/.venv/lib/python3.9/site-packages/pysubs2/formats.py\", line 78, in autodetect_format\n",
      "-->\t    raise FormatAutodetectionError(\"No suitable formats\")\n",
      "-->\tpysubs2.exceptions.FormatAutodetectionError: No suitable formats\n"
     ]
    },
    {
     "output_type": "error",
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_6969/532771042.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mfile\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mtqdm\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiles\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m         \u001b[0mmodels\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSubtitlePersist\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_file\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m         print(\n",
      "\u001b[0;32m~/Documents/SagasuSubs/SagasuSubs/models.py\u001b[0m in \u001b[0;36mfrom_file\u001b[0;34m(cls, file)\u001b[0m\n\u001b[1;32m     38\u001b[0m         \u001b[0mdata\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msha1\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mauto_load\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msha1sum\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     39\u001b[0m         \u001b[0msubtitle\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mSSAFile\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_string\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 40\u001b[0;31m         dialogs = [\n\u001b[0m\u001b[1;32m     41\u001b[0m             DialogContent(\n\u001b[1;32m     42\u001b[0m                 \u001b[0mcontent\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdialog\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtext\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Documents/SagasuSubs/SagasuSubs/models.py\u001b[0m in \u001b[0;36m<listcomp>\u001b[0;34m(.0)\u001b[0m\n\u001b[1;32m     39\u001b[0m         \u001b[0msubtitle\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mSSAFile\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_string\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     40\u001b[0m         dialogs = [\n\u001b[0;32m---> 41\u001b[0;31m             DialogContent(\n\u001b[0m\u001b[1;32m     42\u001b[0m                 \u001b[0mcontent\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdialog\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtext\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     43\u001b[0m                 \u001b[0mbegin\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdialog\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstart\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "metadata": {}
  }
 ],
 "metadata": {
  "orig_nbformat": 4,
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}